# Generated by Django 4.2 on 2026-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sociallinks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='year_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
