# Generated by Django 4.2 on 2026-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_certificate_issued_by_certificate_year_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(default=2026),
        ),
    ]
