# Generated by Django 4.2 on 2026-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.CharField(default='2024-2026', help_text='Enter the batch years in format YYYY-YYYY', max_length=9),
        ),
    ]
