# Generated by Django 4.2 on 2026-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_batch_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch_year',
        ),
        migrations.AddField(
            model_name='student',
            name='passed_out_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
