# Generated by Django 4.2 on 2026-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcoordinator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentcoordinator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
