# Generated by Django 4.2 on 2026-02-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_coordinatormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcoordinator',
            name='programme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
