# Generated by Django 6.0.2 on 2026-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='companyverificationrequest',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
