# Generated by Django 4.2 on 2026-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='graduation_years',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
