# Generated by Django 4.2 on 2026-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_job_graduation_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='programmes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
