# Generated by Django 6.0.2 on 2026-03-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_email_and_more'),
        ('students', '0009_alter_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter', models.FileField(upload_to='offer_letters/')),
                ('message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed_by_student', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offer_letters', to='companies.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='companies.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='students.student')),
            ],
        ),
    ]
